server:
  port: 8081
  servlet:
    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/PeopleSystem
          jwk-set-uri: http://localhost:8083/auth/realms/PeopleSystem/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://peoplesystem.tatdvsonorth.com:5432/peoplesystem
    username: sa
    password: Wawi247525=
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
  # Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: PeopleSystem
  resource: peoplesystem # Ensure this matches your Keycloak client's `client_id`
  public-client: false
  cors: true
  credentials:
    secret: 5jsKBbSmHOTiNksq0H4zh5VMLNluwzv6

  bearer-only: true
  security-constraints:
    - authRoles: default-roles-peoplesystem
      securityCollections:
        - patterns:
            - /* # The paths requiring admin access

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
